[package]
name = "ocelot"
version = "0.1.0"
edition = "2024"

[dependencies]
ocelot-protocol.workspace = true

tokio = { workspace = true, features = ["net", "io-util", "rt-multi-thread", "macros"] }
tokio-util = {workspace = true, features = ["io-util"] }
