[package]
name = "ocelot-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
ocelot-macros.workspace = true

uuid = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
