[package]
name = "ocelot-data"
version = "0.1.0"
edition = "2024"
build = "build/build.rs"

[build-dependencies]
proc-macro2.workspace = true
serde_json.workspace = true
quote.workspace = true
fastnbt.workspace = true
