[package]
name = "ocelot-data"
version.workspace = true
edition.workspace = true
build = "build/build.rs"

[build-dependencies]
proc-macro2.workspace = true
serde_json.workspace = true
quote.workspace = true
fastnbt.workspace = true
